services:
  - type: web
    name: wound-analysis-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: FIREBASE_SERVICE_ACCOUNT_PATH
        value: secret-files/firebase-service-account.json
