# Generated by Django 5.2.9 on 2026-01-29 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_alter_alert_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Medical Record Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, help_text='Hospital ID, e.g., P001', max_length=20, null=True, unique=True),
        ),
    ]
