# Generated by Django 5.2.9 on 2026-01-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_patient_admission_date_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
    ]
