# Generated by Django 5.2.9 on 2026-01-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_patient_assigned_physician'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
