# Generated by Django 5.2.9 on 2026-01-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0007_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woundassessment',
            name='image',
            field=models.TextField(help_text='Base64 encoded image data'),
        ),
    ]
