# Generated by Django 5.2.9 on 2026-01-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0008_alter_woundassessment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wound',
            name='wound_type',
            field=models.CharField(choices=[('Venous Ulcer', 'Venous Ulcer'), ('Pressure Ulcer', 'Pressure Ulcer'), ('Diabetic Foot', 'Diabetic Foot'), ('Surgical', 'Surgical'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
