# Generated by Django 5.2.9 on 2026-02-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0011_patient_assigned_nurse'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='blood_pressure_diastolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='blood_pressure_systolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
