# Generated by Django 5.2.9 on 2026-02-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0012_clinicalrecord_blood_pressure_diastolic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diabetes_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wound',
            name='onset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='woundassessment',
            name='algorithm_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='woundassessment',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='woundassessment',
            name='cure_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='woundassessment',
            name='exudate_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='woundassessment',
            name='healing_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='woundassessment',
            name='length',
            field=models.FloatField(blank=True, help_text='Length in cm', null=True),
        ),
        migrations.AddField(
            model_name='woundassessment',
            name='ml_analysis_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='woundassessment',
            name='pain_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='woundassessment',
            name='reduction_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
