# Generated by Django 5.2.9 on 2026-01-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DISABLED', 'DISABLED')], default='ACTIVE', max_length=20)),
                ('role', models.CharField(choices=[('Clinician', 'Clinician'), ('Researcher', 'Researcher'), ('Admin', 'Admin')], max_length=20)),
                ('activity', models.CharField(blank=True, max_length=50)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
