# Generated by Django 5.2.9 on 2026-01-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Researcher', 'Researcher'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
